[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib"]
remappings = [
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
    "zk-merkle-tree/=node_modules/zk-merkle-tree/",
]

[fmt]
ignore = ["contracts/generated/Verifier.sol"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config