name: Solidity Foundry
on: [pull_request]

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: ./.github/workflows/build.yml
      
      - name: Forge Format
        run: |
          forge fmt --check
        id: format