name: Solidity Foundry
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Set Node.js 18.15
        uses: actions/setup-node@v3
        with:
          node-version: 18.15
      
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Forge Build
        run: |
          forge --version
          forge build --sizes
        id: build

  fmt:
    name: Format
    runs-on: ubuntu-22.04
    needs: build 
    steps:      
      - name: Forge Format
        run: |
          forge fmt --check
        id: format